In [1]:
from algorithms import prime_sieve, primes_chunk, matrix_multiplication, matrix_multiplication_chunk
import numpy as np

from single_runner import bench_matrix_multiplication_single, bench_prime_single

from distributed_runner import bench_primes_multiprocessing, bench_matrix_multiplication_distributed

import visualizations as vis


In [2]:

limit = 100
prime_results = prime_sieve(100)
print(prime_results)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [3]:
prime_res1 = primes_chunk((0, 50))
prime_res2 = primes_chunk((51, 100))
prime_results1 = prime_res1 + prime_res2
print(prime_results1)

print(f'Single is same as multi: {prime_results == prime_results1}')

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
Single is same as multi: True


In [4]:
matrix_res = matrix_multiplication(3)
print(matrix_res)

[[0.84619361 0.86422044 0.6525632 ]
 [0.98908817 0.97987068 0.79147937]
 [0.9219125  1.30143532 1.14513248]]


In [5]:
row_indicies = [0, 1]
size = 3
seed=2026
result_chunk = matrix_multiplication_chunk((row_indicies, size, seed))
print(result_chunk)

matches = np.allclose(matrix_res[row_indicies], result_chunk)
print(matches)

[[0.84619361 0.86422044 0.6525632 ]
 [0.98908817 0.97987068 0.79147937]]
True


In [6]:
prime_single_benchmark = bench_prime_single(100)
matmul_single_benchmark = bench_matrix_multiplication_single(3)

In [7]:
print(prime_single_benchmark)
print(matmul_single_benchmark)

BenchmarkResult(label='single', algorithm='primes', size=100, num_workers=1, elapsed_sec=0.0, peak_memory_mb=134.31, avg_cpu_pct=0.0, speedup=0.0)
BenchmarkResult(label='single', algorithm='matrix multiplication', size=3, num_workers=1, elapsed_sec=0.0001, peak_memory_mb=134.31, avg_cpu_pct=22.7, speedup=0.0)


In [8]:
prime_single_benchmark = bench_prime_single(10000000)
matmul_single_benchmark = bench_matrix_multiplication_single(100)

In [9]:
print(prime_single_benchmark)
print(matmul_single_benchmark)

BenchmarkResult(label='single', algorithm='primes', size=10000000, num_workers=1, elapsed_sec=0.2855, peak_memory_mb=177.75, avg_cpu_pct=10.33, speedup=0.0)
BenchmarkResult(label='single', algorithm='matrix multiplication', size=100, num_workers=1, elapsed_sec=0.0003, peak_memory_mb=163.56, avg_cpu_pct=0.0, speedup=0.0)


In [10]:
prime_mp_benchmark = bench_primes_multiprocessing(10000000, 100)
matmul_mp_benchmark = bench_matrix_multiplication_distributed(100, 5)

In [11]:
print(prime_mp_benchmark)
print(matmul_mp_benchmark)

BenchmarkResult(label='multiprocess-num_workers=100', algorithm='primes', size=10000000, num_workers=100, elapsed_sec=12.2744, peak_memory_mb=188.45, avg_cpu_pct=60.51, speedup=0.0)
BenchmarkResult(label='multiprocess-5', algorithm='matrix multiplication', size=100, num_workers=5, elapsed_sec=0.1139, peak_memory_mb=186.56, avg_cpu_pct=42.75, speedup=0.0)


In [13]:
df = vis.result_to_df([prime_mp_benchmark])
display(df)
vis.plot_exec_time(df, 'primes', 10000000)

,label,algorithm,size,num_workers,elapsed_sec,peak_memory_mb,avg_cpu_pct,speedup
0,multiprocess-num_workers=100,primes,10000000,100,12.2744,188.45,60.51,0.0


Saved: /Users/jackson/Library/CloudStorage/OneDrive-UniversityofNewBrunswick/UNIVERSITY/4TH YEAR 2025 - 2026/2ND SEMESTER/CS3813 Computer Architecture and Organization/Final Project/src/python/../results/exec_time_primes_10000000.png
