In [ ]:
from algorithms import prime_sieve, primes_chunk, matrix_multiplication, matrix_multiplication_chunk
import numpy as np

from single_runner import bench_matrix_multiplication_single, bench_prime_single

from distributed_runner import bench_primes_multiprocessing, bench_matrix_multiplication_distributed


In [25]:

limit = 100
prime_results = prime_sieve(100)
print(prime_results)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [26]:
prime_res1 = primes_chunk((0, 50))
prime_res2 = primes_chunk((51, 100))
prime_results1 = prime_res1 + prime_res2
print(prime_results1)

print(f'Single is same as multi: {prime_results == prime_results1}')

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
Single is same as multi: True


In [27]:
matrix_res = matrix_multiplication(3)
print(matrix_res)

[[0.84619361 0.86422044 0.6525632 ]
 [0.98908817 0.97987068 0.79147937]
 [0.9219125  1.30143532 1.14513248]]


In [28]:
row_indicies = [0, 1]
size = 3
seed=2026
result_chunk = matrix_multiplication_chunk((row_indicies, size, seed))
print(result_chunk)

matches = np.allclose(matrix_res[row_indicies], result_chunk)
print(matches)

[[0.84619361 0.86422044 0.6525632 ]
 [0.98908817 0.97987068 0.79147937]]
True


In [29]:
prime_single_benchmark = bench_prime_single(100)
matmul_single_benchmark = bench_matrix_multiplication_single(3)

In [30]:
print(prime_single_benchmark)
print(matmul_single_benchmark)

BenchmarkResult(label='single', algorithm='primes', size=100, num_workers=1, elapsed_sec=0.0, peak_memory_mb=92.7, avg_cpu_pct=21.0, speedup=0.0)
BenchmarkResult(label='single', algorithm='matrix multiplication', size=3, num_workers=1, elapsed_sec=0.0001, peak_memory_mb=92.7, avg_cpu_pct=29.0, speedup=0.0)


In [39]:
prime_single_benchmark = bench_prime_single(10000000)
matmul_single_benchmark = bench_matrix_multiplication_single(100)

In [40]:
print(prime_single_benchmark)
print(matmul_single_benchmark)

BenchmarkResult(label='single', algorithm='primes', size=10000000, num_workers=1, elapsed_sec=0.279, peak_memory_mb=137.28, avg_cpu_pct=27.0, speedup=0.0)
BenchmarkResult(label='single', algorithm='matrix multiplication', size=100, num_workers=1, elapsed_sec=0.0004, peak_memory_mb=125.5, avg_cpu_pct=21.7, speedup=0.0)


In [ ]:
prime_mp_benchmark = bench_primes_multiprocessing(10000000, 100)
matmul_mp_benchmark = bench_matrix_multiplication_distributed(100, 5)

In [ ]:
print(prime_mp_benchmark)
print(matmul_mp_benchmark)

BenchmarkResult(label='multiprocess-num_workers=100', algorithm='primes', size=10000000, num_workers=100, elapsed_sec=12.2442, peak_memory_mb=165.53, avg_cpu_pct=70.01, speedup=0.0)
