In [3]:
from algorithms import prime_sieve, primes_chunk, matrix_multiplication, matrix_multiplication_chunk
import numpy as np


In [4]:

limit = 100
prime_results = prime_sieve(100)
print(prime_results)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [5]:
prime_res1 = primes_chunk((0, 50))
prime_res2 = primes_chunk((51, 100))
prime_results1 = prime_res1 + prime_res2
print(prime_results1)

print(f'Single is same as multi: {prime_results == prime_results1}')

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
Single is same as multi: True


In [6]:
matrix_res = matrix_multiplication(3)
print(matrix_res)

[[0.84619361 0.86422044 0.6525632 ]
 [0.98908817 0.97987068 0.79147937]
 [0.9219125  1.30143532 1.14513248]]


In [7]:
row_indicies = [0, 1]
size = 3
seed=2026
result_chunk = matrix_multiplication_chunk((row_indicies, size, seed))
print(result_chunk)

matches = np.allclose(matrix_res[row_indicies], result_chunk)
print(matches)

[[0.84619361 0.86422044 0.6525632 ]
 [0.98908817 0.97987068 0.79147937]]
True
